[debug] [2018-12-23T18:31:53.862Z] ----------------------------------------------------------------------
[debug] [2018-12-23T18:31:53.865Z] Command:       /usr/bin/node /usr/local/bin/firebase login
[debug] [2018-12-23T18:31:53.865Z] CLI Version:   6.2.2
[debug] [2018-12-23T18:31:53.865Z] Platform:      linux
[debug] [2018-12-23T18:31:53.865Z] Node Version:  v8.11.2
[debug] [2018-12-23T18:31:53.865Z] Time:          Sun Dec 23 2018 19:31:53 GMT+0100 (CET)
[debug] [2018-12-23T18:31:53.865Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=698200970&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-12-23T18:32:11.436Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2018-12-23T18:32:11.525Z] Token Fetch Error: Error
    at new FirebaseError (/usr/local/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:28:31)
    at self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-12-23T18:32:44.391Z] ----------------------------------------------------------------------
[debug] [2018-12-23T18:32:44.394Z] Command:       /usr/bin/node /usr/local/bin/firebase login
[debug] [2018-12-23T18:32:44.394Z] CLI Version:   6.2.2
[debug] [2018-12-23T18:32:44.394Z] Platform:      linux
[debug] [2018-12-23T18:32:44.394Z] Node Version:  v8.11.2
[debug] [2018-12-23T18:32:44.394Z] Time:          Sun Dec 23 2018 19:32:44 GMT+0100 (CET)
[debug] [2018-12-23T18:32:44.394Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=144820116&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-12-23T18:33:01.449Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2018-12-23T18:33:01.530Z] Token Fetch Error: Error
    at new FirebaseError (/usr/local/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:28:31)
    at self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
